PGG_Base/PGG0/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)

author = 'jrm'

doc = """
PGG 0 - Basic public goods game
"""


class Constants(BaseConstants):
    name_in_url = 'PGG0'
    players_per_group = 4
    num_rounds = 2
    num_rounds_range = range(num_rounds)

    endowment = c(20)
    multiplier = 2


class Subsession(BaseSubsession):
    pass





class Group(BaseGroup):
    total_contribution = models.IntegerField()
    total_payoff = models.IntegerField()

    def public_good_per_player(self):
        all_contrib = 0
        for p in self.get_players():
            all_contrib += p.contribution
        return (1 / Constants.players_per_group) * Constants.multiplier * all_contrib

    def calculate_total_contribution(self):
        all_contrib = 0
        for p in self.get_players():
            all_contrib += p.contribution
        self.total_contribution = all_contrib


class Player(BasePlayer):
    contribution = models.IntegerField(
        min=0, max=Constants.endowment,
        doc="""The amount contributed by the player""",
    )

    def in_all_rounds_full_range(self):
        empty_list_tail = [None] * (Constants.num_rounds - len(self.in_all_rounds()))
        return self.in_all_rounds() + empty_list_tail

    def calculate_payoff(self):
        self.payoff = Constants.endowment - self.contribution \
                      + self.group.public_good_per_player()

PGG_Base/PGG_Base_Questionnaire/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


author = 'JRM'

doc = """
Questionnaire and final summary of total earnings
"""


class Constants(BaseConstants):
    name_in_url = 'PGG_Base_Questionnaire'
    players_per_group = 4
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    # Questionnaire part 1
    # What is your gender?
    gender = models.StringField(
        choices=['Female', 'Male'],
        widget=widgets.RadioSelect,
        label=""
    )

    # What is your age?
    age = models.IntegerField(
        min=1,
        label=""
    )

    # Your highest education
    education = models.StringField(
        choices=['Qualifications for University Entrance', 'Bachelor', 'Master', 'Doctor', 'Other'],
        widget=widgets.RadioSelect,
        label=""
    )

    # Questionnaire part 2
    question_4a = models.StringField(
        choices=['Yes','No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_4b = models.LongStringField(label="")
    question_5a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_5 = models.LongStringField(label="")
    question_6a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_6 = models.LongStringField(label="")
    question_7 = models.LongStringField(label="")

    # Questionnaire part 3
    question_8a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_8x = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_8 = models.LongStringField(label="")
    question_9a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_9x = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_9 = models.LongStringField(label="")
    question_10a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_10 = models.LongStringField(label="")


    question_11a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_11 = models.LongStringField(label="")
    question_12a = models.StringField(
        choices=['Yes', 'No'],
        widget=widgets.RadioSelect,
        label=""
    )
    question_12 = models.LongStringField(label="")

    prolificID_Input = models.StringField(label="")

PGG_Base/PGG0/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()



PGG_Base/PGG0/views.py
from otree.api import Currency as c, currency_range
from . import models
from ._builtin import Page, WaitPage
from .models import Constants


class Instructions(Page):
    def is_displayed(self):
        return self.round_number == 1


class Contribution(Page):
    form_model = 'player'
    form_fields = ['contribution']


class ResultsWaitPage(WaitPage):
    def after_all_players_arrive(self):
        self.group.calculate_total_contribution()
        for p in self.group.get_players():
            p.calculate_payoff()


class SummaryPage(Page):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds

    def vars_for_template(self):
        total_payoff = 0
        for r in self.player.in_all_rounds():
            total_payoff += r.payoff
        return {'total_payoff': total_payoff}


class Results(Page):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds

    def vars_for_template(self):
        total_payoff = 0
        for r in self.player.in_all_rounds():
            total_payoff += r.payoff
        return {'total_payoff': total_payoff}

    def before_next_page(self):
        total_payoff = 0
        for r in self.player.in_all_rounds():
            total_payoff += r.payoff
        self.participant.vars['total_payoff_PGG0'] = total_payoff
        self.participant.vars['PGG_number'] = 0
        self.participant.vars['player_role'] = "manager" if self.player.role() == "manager" else "peer"


class NextApp(Page):

    def is_displayed(self):
        return self.round_number == Constants.num_rounds

    def before_next_page(self):
        total_payoff = 0
        for r in self.player.in_all_rounds():
            total_payoff += r.payoff
        self.participant.vars['total_payoff_PGG0'] = total_payoff


page_sequence = [
    Instructions,
    Contribution,
    ResultsWaitPage,
    #SummaryPage,
    Results
    #NextApp
]

PGG_Base/PGG_Base_Questionnaire/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api


class Page(otree.api.Page):
    subsession: models.Subsession
    group: models.Group
    player: models.Player


class WaitPage(otree.api.WaitPage):
    subsession: models.Subsession
    group: models.Group


class Bot(otree.api.Bot):
    subsession: models.Subsession
    group: models.Group
    player: models.Player

PGG_Base/PGG0/templates/PGG0/Contribution.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

    <link href="{% static "PGG0/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }
    </style>

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG0/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Contribute</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li class="navbar-text" style="padding-right: 10px">
                <img src="{% static "PGG0/contribute_here.png" %}" height="20">
            </li>
            <input type="number" name="contribution" required step="1" min="0" max="20" id="id_contribution"
                   class="form-control" style="width: 80px; height: 38px">
            <li>
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Submit</button>
            </li>
        </ul>
    </nav>

    <h4 style="margin-top: 20px">Contributions <span style="font-size: small; color: blue; padding-left: 10px">C: contributions, E: earnings</span></h4>
    {% include "PGG0/ContributionTable.html" %}

{% endblock %}

PGG_Base/PGG0/templates/PGG0/ContributionTable.html
<style>

    table, th, td {
        border: 1px solid black;
    }

    table {
        font-size: small;
        text-align: center;
    }

    #table-header td:nth-child({{ player.round_number|add:'1' }}) {
        background: #350FFF;
        color: white;
    }

    #contribution-table tr:nth-child({{ player.id_in_group|add:'2' }}) {
        background: #350FFF77;
        color: white;
    }

</style>


<table id="contribution-table" style="table-layout: fixed; width: 100%">
    <tr id="table-header">
        <td>Round:</td>
        {% for r in Constants.num_rounds_range %}
            <td colspan="2">{{ r|add:'1' }}</td>
        {% endfor %}
    </tr>

    <tr>
        <td></td>
        {% for r in Constants.num_rounds_range %}
            <td>C</td>
            <td>E</td>
        {% endfor %}
    </tr>

    {% for p in group.get_players %}
        <tr>
            <th>
                Player
                {{ p.id_in_group }}
                {% if p.id_in_group == player.id_in_group %} (You) {% endif %}
            </th>
            {% for r in p.in_all_rounds_full_range %}
                {% if r != None and r.contribution != None %}
                    <td>{{ r.contribution }}</td>
                    <td>{{ r.payoff}}</td>
                {% else %}
                    <td></td>
                    <td></td>
                {% endif %}
            {% endfor %}
        </tr>
    {% endfor %}

    <tr>
        <th>
            Sum
        </th>
        {% for r in player.in_all_rounds_full_range %}
            {% if r.group.total_contribution != None %}
                <td>{{ r.group.total_contribution }}</td>
                <td></td>
            {% else %}
                <td></td>
                <td></td>
            {% endif %}
        {% endfor %}
    </tr>
</table>

PGG_Base/PGG0/templates/PGG0/Instructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}


{% block styles %}

    <link href="{% static "PGG0/styles.css" %}" rel="stylesheet">

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGGM_Teaching/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Instructions</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li class="navbar-text" style="padding-right: 10px">
            </li>
            <li style="padding-right: 10px">{{ form.contribution }}</li>
{#            <li>#}
{#                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Start</button>#}
{#            </li>#}
        </ul>
    </nav>

    <div class="instructions well well-lg">
<p>
Thank you for participating in today’s experiment. Please switch off your cell phone, do not talk to other participants, and do not communicate with others using the PC. You have been randomly assigned to a group of 4 people – but will only conduct this experiment by yourself. The members of the group do not change during the experiment. You will not be made aware of the identity of the others in your group (or any other group) at any time – neither will anyone else be made aware of your identity. Everyone in the group receives 20 tokens as an endowment in every round. 20 tokens correspond to $ 0.50 (USD); 1 token corresponds to $ 0.02 (USD). In the experiment you can freely decide how much of this amount to keep for yourself and how much to contribute to the group account. You do that by typing your chosen contribution in the input field in the top right corner on the page and press “Submit”. Everyone in the group will make the same type of decision, and everyone is allowed to contribute any amount between 0 and 20 tokens, only integers. The sum of all contributions will be doubled and the resulting total amount in the group account will then be equally divided among the four persons in the group, i.e. everyone in the group receives 25% of the group account irrespective of this person’s contribution. The share that you receive from the group account will then be added to the amount that you decided to keep for yourself. Note that the group account is always zero after everyone’s shares have been distributed at the end of each round.
</p>
<p>
You will engage in this experiment over 10 rounds. In every round, you and the other group members will receive 20 tokens. All members of the group will make the same type of decision in every round, i.e. you decide how much you will keep for yourself and how much you will contribute to the group account. In each round the contributions will be doubled before the shares are paid out to the group member. The main information is displayed to everyone using the following abbreviations:
</p>


 <table>
            <tr>
                <td><b>C</b></td>
                <td><b><i>Contributions</i></b></td>
                <td>What everyone has contributed in a given round</td>
            </tr>
            <tr>
                <td><b>E</b></td>
                <td><b><i>Earnings</i></b></td>
                <td>What everyone has earned in a given round</td>
            </tr>
        </table>
        <div class="imgBlockStyle">
            <img src="{% static "PGG0/contribution_input_field.png" %}" width="600">
        </div>

<p>
This is the end of the instructions. By pressing the ‘Next’ button we assume you have read and understood the instructions of the experiment. Please do not close the browser at any time. After you have completed the 10 rounds, you will need to complete a questionnaire before you can check out. Your final earnings are your accumulated earnings after round 10, i.e. all the amounts that you decided to keep for yourself plus the returns you received from the group account.
</p>
<p>
As you prepare to start with the experiment, please be patient as others need to finish reading the instructions. It may also take some time to compile data on the server.
</p>
<p>
Please, press ‘Next’ and continue with the experiment.
</p>



<button class="otree-btn-next btn btn-primary nextBtnPlacement">Next</button>

    </div>

{% endblock %}

PGG_Base/PGG0/templates/PGG0/NextApp.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

    <link href="{% static "PGG0/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }
    </style>

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG0/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Contribute</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li class="navbar-text" style="padding-right: 10px">
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Next</button>
            </li>
        </ul>
    </nav>

    <h4 style="margin-top: 20px"> Please press "Next" to continue to the questionnaire. </h4>

{% endblock %}

PGG_Base/PGG0/templates/PGG0/Results.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

    <link href="{% static "PGG0/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }
    </style>

{% endblock %}


{% block content %}

  <nav id="navbar-main" class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG2/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Summary</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li>
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Continue</button>
            </li>
        </ul>
    </nav>


    <h4 style="margin-top: 20px">Contributions <span style="font-size: small; color: blue; padding-left: 10px">C: contributions, E: earnings</span></h4>
    {% include "PGG0/ContributionTable.html" %}

    <div style="padding: 30px; text-align: center">
        Your total payoff is <b>{{ total_payoff }}</b>
    </div>

{% endblock %}

PGG_Base/PGG0/templates/PGG0/SummaryPage.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}


{% block app_styles %}

    <link href="{% static "PGG2/styles.css" %}" rel="stylesheet">

    <style>

        #game-info-tables{
            position: fixed;
            top: 130px;
        }

        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }

        #punish-or-reward-div {
            margin-left: -50px;
            margin-right: -50px;
            padding-right: 50px;
            overflow: hidden;
            background-color: #350FFF;
            position: fixed;
        }

        #punish-or-reward-table th {
            border-right: dashed 2px;
            text-align: center;
        }

        #punish-or-reward-table th:last-child {
            border-right: none;
        }

        #punish-or-reward-table td:nth-child(3n+0) {
            border-right: dashed 2px;
        }

        #punish-or-reward-table td:last-child {
            border-right: none;
        }

        #contribution-table th {
            overflow-wrap: break-word;
            word-wrap: break-word;

            -ms-hyphens: auto;
            -moz-hyphens: auto;
            -webkit-hyphens: auto;
            hyphens: auto;
        }

        #contribution-table {
            font-size: x-small;
            text-align: center;
        }

        #contribution-table th, #contribution-table td {
            border: 1px solid black;
        }

        #table-header td:nth-child({{ player.round_number|add:'1' }}) {
            background: #350FFF;
            color: white;
        }

    </style>

{% endblock %}


{% block content %}

    <nav id="navbar-main" class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG2/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Summary</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li>
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Continue</button>
            </li>
        </ul>
    </nav>

    <div id="game-info-tables">
        <h4>Contributions</h4>
        <table id="contribution-table" style="table-layout: fixed; width: 100%">
            <tr id="table-header">
                <td>Round:</td>
                {% for r in Constants.num_rounds_range %}
                    <td colspan="2">{{ r|add:'1' }}</td>
                {% endfor %}
            </tr>

            <tr>
                <td></td>
                {% for r in Constants.num_rounds_range %}
                    <td>C</td>
                    <td>E</td>
                {% endfor %}
            </tr>

            <tbody>
            <tr>
                <td><strong>You (Player {{ player.id_in_group }})</strong></td>
                {% for p in player.in_all_rounds %}
                    <td>{{ p.contribution }}</td>
                    <td>{{ p.payoff }}</td>
                {% endfor %}
            </tr>
            {% for others in player.get_others_in_group %}
                <tr>
                    <td>Player {{ others.id_in_group }}</td>
                    {% for p in others.in_all_rounds %}
                        <td>{{ p.contribution }}</td>
                        <td>{{ p.payoff }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

{% endblock %}


{% block scripts %}

    <script>

        $(document).ready(function () {
            document.getElementById("punish-or-reward-div").style.top =
            document.getElementById("navbar-main").offsetHeight + "px"
        })

    </script>

{% endblock %}


PGG_Base/PGG_Base_Questionnaire/templates/PGG_Base_Questionnaire/EndPage.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

    <link href="{% static "PGG5/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }

        table {
            margin-left: auto;
            margin-right: auto;
        }

        table td {
            padding-left: 5vw;
            padding-right: 5vw;
        }

    </style>

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG5/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Finished</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li class="navbar-text" style="padding-right: 10px">
                Finished
            </li>
        </ul>
    </nav>

    <div style="padding: 30px; text-align: center">
        Dies ist das Ende des Experiments. Bitte wenden Sie sich jetzt an einen Labor-Betreuer. Vielen Dank!
    </div>


{% endblock %}

PGG_Base/PGG_Base_Questionnaire/templates/PGG_Base_Questionnaire/FinalPage.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

    <link href="{% static "PGG5/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }

        table {
            margin-left: auto;
            margin-right: auto;
        }

        table td {
            padding-left: 5vw;
            padding-right: 5vw;
        }
    </style>

{% endblock %}


{% block content %}
 <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG5/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Summary</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li class="navbar-text" style="padding-right: 10px">
                Finished
            </li>
        </ul>
    </nav>

    <div style="padding: 30px; text-align: center">
        This is the end of the experiment. Your earnings are:
    </div>
    <table>
        <tr>
            <td>Experiment Earnings </td>
            <td>{{ total_payoff_overall }}</td>
        </tr>
        <tr>
            <td>Your total payment</td>
            <td>{{ total_payment }}</td>
        </tr>
    </table>

<div style="padding: 30px; text-align: center">

        <p>Thank you for participating in this experiment</p>
   </div>

{% endblock %}


PGG_Base/PGG_Base_Questionnaire/templates/PGG_Base_Questionnaire/QuestionnairePart1.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

   <link href="{% static "PGG5/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }
    </style>

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src={% static "PGG5/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Questionnaire</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li>
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Next</button>
            </li>
        </ul>
    </nav>

    <div class="instructions well well-lg">
        <p>

Please answer the following questions honestly and according to your personal impressions and experiences.
            Your answers will be kept confidential and are of particular importance to the experiment
        </p>
        <p>
If you have any questions please raise your hand and a supervisor can assist you. Thank you for your participation.
        </p>
    </div>

    <p>What is your gender?</p>
    <div class="form-control" style="width: 20vw; height: 38px; margin-bottom: 50px">{% formfield player.gender %}</div>


    <p>How old are you?</p>
    <div class="form-control" style="width: 9vw; height: 53px; margin-bottom: 50px; background-color: #3500D3">{% formfield player.age %}</div>

    <p>What is your highest completed level of eduction?</p>
    <div class="form-control" style="width: 20vw; height: 38px; margin-bottom: 150px">{% formfield player.education %}</div>

{% endblock %}

PGG_Base/PGG_Base_Questionnaire/templates/PGG_Base_Questionnaire/QuestionnairePart2.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load static %}


{% block app_styles %}

   <link href="{% static "PGG5/styles.css" %}" rel="stylesheet">

    <style>
        .otree-btn-next {
            margin: 0px;
        }

        .form-control {
            border-color: white;
        }

        .form-control:focus {
            border-color: #3500D3;
        }

        .questions {
            border: 1px solid #3500D3;
            width: 40vw;
            padding: 1px;
        }

        .input-area textarea {
            border: 10px solid #3500D3;
        }
    </style>

{% endblock %}


{% block content %}

    <nav class="navbar fixed-top navbar-dark" style="background-color: #3500D3">
        <a class="navbar-brand" href="#"><img src="{% static "PGG5/pgg_logo.png" %}" height="30px"
                                              style="padding-right: 10px">Questionnaire</a>
        <ul class="nav navbar-nav navbar-right" style="flex-direction: row">
            <li>
                <button class="btn btn-primary otree-btn-next btn-outline-light" type="submit">Next</button>
            </li>
        </ul>
    </nav>


<p>How did you try to maximize your payout in the rounds? Please explain your strategy: </p>
<div class="form-control input-area" style="margin-bottom: 50px">{% formfield player.question_7 %}</div>
<p>Please enter your Prolific ID – it has 24 alphanumeric characters and is needed to correctly allocate the above earnings:</p>
<div class="form-control input-area" style="margin-bottom: 50px">{% formfield player.prolificID_Input%}</div>


{% endblock %}